"""Add Requests Count to Tasks

Revision ID: 07ae35c59ccf
Revises: 28b372eee918
Create Date: 2023-01-12 09:26:45.260890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ae35c59ccf'
down_revision = '28b372eee918'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('requests', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', sa.Column('requests'))
    # ### end Alembic commands ###
