"""Add User-Task relation

Revision ID: 43c464843847
Revises: 
Create Date: 2023-02-23 16:10:40.886066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c464843847'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False, server_default=str(1)))
    op.create_unique_constraint(None, 'tasks', ['base_filename'])
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'workers', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
